"""add_name_and_brand_id_to_interesting_products

Revision ID: 01650e81bda7
Revises: 4bd2ca968a6f
Create Date: 2026-01-03 20:13:58.331705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01650e81bda7'
down_revision: Union[str, None] = '4bd2ca968a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interesting_products', sa.Column('name', sa.String(), nullable=True))
    op.add_column('interesting_products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interesting_products', 'brands', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interesting_products', type_='foreignkey')
    op.drop_column('interesting_products', 'brand_id')
    op.drop_column('interesting_products', 'name')
    # ### end Alembic commands ###
