"""add_shop_table_and_update_scan_event

Revision ID: 049dd2791691
Revises: 01650e81bda7
Create Date: 2026-01-04 19:42:53.221088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049dd2791691'
down_revision: Union[str, None] = '01650e81bda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('osm_id', sa.String(), nullable=True),
    sa.Column('osm_type', sa.String(), nullable=True),
    sa.Column('shop_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.create_index(op.f('ix_shops_latitude'), 'shops', ['latitude'], unique=False)
    op.create_index(op.f('ix_shops_longitude'), 'shops', ['longitude'], unique=False)
    op.create_index(op.f('ix_shops_name'), 'shops', ['name'], unique=False)
    op.create_index(op.f('ix_shops_osm_id'), 'shops', ['osm_id'], unique=True)
    op.add_column('scan_events', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_scan_events_shop_id'), 'scan_events', ['shop_id'], unique=False)
    op.create_foreign_key(None, 'scan_events', 'shops', ['shop_id'], ['id'])
    op.drop_column('scan_events', 'shop_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_events', sa.Column('shop_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scan_events', type_='foreignkey')
    op.drop_index(op.f('ix_scan_events_shop_id'), table_name='scan_events')
    op.drop_column('scan_events', 'shop_id')
    op.drop_index(op.f('ix_shops_osm_id'), table_name='shops')
    op.drop_index(op.f('ix_shops_name'), table_name='shops')
    op.drop_index(op.f('ix_shops_longitude'), table_name='shops')
    op.drop_index(op.f('ix_shops_latitude'), table_name='shops')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###
