"""Add Checkings Table

Revision ID: 0a2cb99fef78
Revises: d73e0c2d0933
Create Date: 2025-07-29 12:48:10.483586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a2cb99fef78'
down_revision: Union[str, None] = 'd73e0c2d0933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('requested_on', sa.DateTime(), nullable=True),
    sa.Column('responded_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VEGAN', 'NON_VEGAN', name='checkingstatus'), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkings_id'), 'checkings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkings_id'), table_name='checkings')
    op.drop_table('checkings')
    # ### end Alembic commands ###
