"""Add Household cleaners

Revision ID: 0bc3352d9ae1
Revises: 049dd2791691
Create Date: 2026-01-17 17:29:32.000408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc3352d9ae1'
down_revision: Union[str, None] = '049dd2791691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_cleaners',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('brand_name', sa.String(), nullable=False),
                    sa.Column('is_vegan', sa.Boolean(), nullable=True),
                    sa.Column('is_cruelty_free', sa.Boolean(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('source', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_household_cleaners_brand_name'),
                    'household_cleaners', ['brand_name'], unique=True)
    op.create_index(op.f('ix_household_cleaners_id'),
                    'household_cleaners', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_household_cleaners_id'),
                  table_name='household_cleaners')
    op.drop_index(op.f('ix_household_cleaners_brand_name'),
                  table_name='household_cleaners')
    op.drop_table('household_cleaners')
    # ### end Alembic commands ###
