"""add infos to users

Revision ID: 204570058722
Revises: 6e532ca385bd
Create Date: 2025-10-21 17:38:28.827145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204570058722'
down_revision: Union[str, None] = '6e532ca385bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vegan_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('nb_products_sent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nb_products_sent')
    op.drop_column('users', 'vegan_since')
    # ### end Alembic commands ###
