"""Add reviews

Revision ID: 2235473e3bc4
Revises: 554341a6cf69
Create Date: 2026-03-28 14:44:35.334713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2235473e3bc4'
down_revision: Union[str, None] = '554341a6cf69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_not_found_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_not_found_reports_date_created'), 'product_not_found_reports', ['date_created'], unique=False)
    op.create_index(op.f('ix_product_not_found_reports_ean'), 'product_not_found_reports', ['ean'], unique=False)
    op.create_index(op.f('ix_product_not_found_reports_id'), 'product_not_found_reports', ['id'], unique=False)
    op.create_index(op.f('ix_product_not_found_reports_shop_id'), 'product_not_found_reports', ['shop_id'], unique=False)
    op.create_table('shop_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='shopreviewstatus'), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_shop_review_rating'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'user_id', name='uq_shop_review_shop_user')
    )
    op.create_index(op.f('ix_shop_reviews_date_created'), 'shop_reviews', ['date_created'], unique=False)
    op.create_index(op.f('ix_shop_reviews_id'), 'shop_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_shop_reviews_shop_id'), 'shop_reviews', ['shop_id'], unique=False)
    op.create_index(op.f('ix_shop_reviews_status'), 'shop_reviews', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_reviews_status'), table_name='shop_reviews')
    op.drop_index(op.f('ix_shop_reviews_shop_id'), table_name='shop_reviews')
    op.drop_index(op.f('ix_shop_reviews_id'), table_name='shop_reviews')
    op.drop_index(op.f('ix_shop_reviews_date_created'), table_name='shop_reviews')
    op.drop_table('shop_reviews')
    op.drop_index(op.f('ix_product_not_found_reports_shop_id'), table_name='product_not_found_reports')
    op.drop_index(op.f('ix_product_not_found_reports_id'), table_name='product_not_found_reports')
    op.drop_index(op.f('ix_product_not_found_reports_ean'), table_name='product_not_found_reports')
    op.drop_index(op.f('ix_product_not_found_reports_date_created'), table_name='product_not_found_reports')
    op.drop_table('product_not_found_reports')
    # ### end Alembic commands ###
