"""Added the background field to the Brand table

Revision ID: 2e9429018104
Revises: eab9d5824d95
Create Date: 2026-01-22 16:57:36.293864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9429018104'
down_revision: Union[str, None] = 'eab9d5824d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('background', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'background')
    # ### end Alembic commands ###
