"""add nb products modified to users

Revision ID: 3413005589e3
Revises: 61f56315b444
Create Date: 2025-12-29 20:24:06.999455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3413005589e3'
down_revision: Union[str, None] = '61f56315b444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nb_products_modified', sa.Integer(), nullable=True))
    # Set default value for existing users
    op.execute("UPDATE users SET nb_products_modified = 0 WHERE nb_products_modified IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nb_products_modified')
    # ### end Alembic commands ###
