"""Add created by in shops

Revision ID: 394144a22c93
Revises: 2235473e3bc4
Create Date: 2026-04-03 09:21:51.071630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394144a22c93'
down_revision: Union[str, None] = '2235473e3bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shops_created_by'), 'shops', ['created_by'], unique=False)
    op.create_foreign_key(None, 'shops', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_index(op.f('ix_shops_created_by'), table_name='shops')
    op.drop_column('shops', 'created_by')
    # ### end Alembic commands ###
