"""Add scoring system and brand logo

Revision ID: 43bc3c65e6f0
Revises: a33fad4505eb
Create Date: 2025-09-08 18:20:40.066355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43bc3c65e6f0'
down_revision: Union[str, None] = 'a33fad4505eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_categories_id'), 'scoring_categories', ['id'], unique=False)
    op.create_index(op.f('ix_scoring_categories_name'), 'scoring_categories', ['name'], unique=True)
    op.create_table('scoring_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['scoring_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_criteria_id'), 'scoring_criteria', ['id'], unique=False)
    op.create_index(op.f('ix_scoring_criteria_name'), 'scoring_criteria', ['name'], unique=False)
    op.create_table('brand_criterion_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['criterion_id'], ['scoring_criteria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'criterion_id', name='unique_brand_criterion_score')
    )
    op.create_index(op.f('ix_brand_criterion_scores_id'), 'brand_criterion_scores', ['id'], unique=False)
    op.add_column('brands', sa.Column('logo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'logo_path')
    op.drop_index(op.f('ix_brand_criterion_scores_id'), table_name='brand_criterion_scores')
    op.drop_table('brand_criterion_scores')
    op.drop_index(op.f('ix_scoring_criteria_name'), table_name='scoring_criteria')
    op.drop_index(op.f('ix_scoring_criteria_id'), table_name='scoring_criteria')
    op.drop_table('scoring_criteria')
    op.drop_index(op.f('ix_scoring_categories_name'), table_name='scoring_categories')
    op.drop_index(op.f('ix_scoring_categories_id'), table_name='scoring_categories')
    op.drop_table('scoring_categories')
    # ### end Alembic commands ###
