"""add_product_category_interesting_product_scan_event_tables

Revision ID: 4bd2ca968a6f
Revises: db1c492c81be
Create Date: 2026-01-03 19:05:08.536611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd2ca968a6f'
down_revision: Union[str, None] = 'db1c492c81be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    op.create_table('interesting_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ean', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('popular', 'sponsored', name='interestingproducttype'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interesting_products_ean'), 'interesting_products', ['ean'], unique=False)
    op.create_index(op.f('ix_interesting_products_id'), 'interesting_products', ['id'], unique=False)
    op.create_table('scan_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('ean', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('shop_name', sa.String(), nullable=True),
    sa.Column('lookup_api_response', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_events_ean'), 'scan_events', ['ean'], unique=False)
    op.create_index(op.f('ix_scan_events_id'), 'scan_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_events_id'), table_name='scan_events')
    op.drop_index(op.f('ix_scan_events_ean'), table_name='scan_events')
    op.drop_table('scan_events')
    op.drop_index(op.f('ix_interesting_products_id'), table_name='interesting_products')
    op.drop_index(op.f('ix_interesting_products_ean'), table_name='interesting_products')
    op.drop_table('interesting_products')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
