"""add_discount_code_to_partners

Revision ID: 53607864588d
Revises: 8acfba1eae2d
Create Date: 2026-02-14 19:28:06.799597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53607864588d'
down_revision: Union[str, None] = '8acfba1eae2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('discount_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'discount_code')
    # ### end Alembic commands ###
