"""Add alternative eans

Revision ID: 554341a6cf69
Revises: edc5cba73e76
Create Date: 2026-03-16 18:12:26.473685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554341a6cf69'
down_revision: Union[str, None] = 'edc5cba73e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('interesting_product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'interesting_products', ['interesting_product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'interesting_product_id')
    # ### end Alembic commands ###
