"""add_non_vegan_old_receipe_to_products

Revision ID: 5af6f05dfe64
Revises: ebc246d36080
Create Date: 2025-11-01 19:11:15.825447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af6f05dfe64'
down_revision: Union[str, None] = 'ebc246d36080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('has_non_vegan_old_receipe', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'has_non_vegan_old_receipe')
    # ### end Alembic commands ###
