"""add supporter to users and created_by to error_reports

Revision ID: 61f56315b444
Revises: 9bff3ccb268c
Create Date: 2025-11-08 08:06:52.376087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f56315b444'
down_revision: Union[str, None] = '9bff3ccb268c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supporter', sa.SmallInteger(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'supporter')
    # ### end Alembic commands ###
