"""Add boycott field to brands

Revision ID: 68751ca36f4d
Revises: 43bc3c65e6f0
Create Date: 2025-09-25 20:10:44.663632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68751ca36f4d'
down_revision: Union[str, None] = '43bc3c65e6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('boycott', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'boycott')
    # ### end Alembic commands ###
