"""add subscription tables

Revision ID: 6ee8dd0febcd
Revises: c8d945fee32d
Create Date: 2026-02-28 10:20:59.634963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee8dd0febcd'
down_revision: Union[str, None] = 'd42ec2874557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('platform', sa.Enum('APPLE', 'GOOGLE',
                                                  name='subscriptionplatform'), nullable=False),
                    sa.Column('original_transaction_id',
                              sa.String(), nullable=False),
                    sa.Column('transaction_id', sa.String(), nullable=True),
                    sa.Column('purchase_token', sa.String(), nullable=True),
                    sa.Column('product_id', sa.String(), nullable=False),
                    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED',
                                                'GRACE_PERIOD', name='subscriptionstatus'), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_subscriptions_id'),
                    'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_original_transaction_id'),
                    'subscriptions', ['original_transaction_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'),
                    'subscriptions', ['user_id'], unique=False)
    op.create_table('subscription_events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('subscription_id', sa.Integer(), nullable=False),
                    sa.Column('event_type', sa.Enum('INITIAL_PURCHASE', 'RENEWAL', 'CANCELLATION',
                                                    'EXPIRY', 'REFUND', 'GRACE_PERIOD', name='subscriptioneventtype'), nullable=False),
                    sa.Column('platform_event_data', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['subscription_id'], [
                        'subscriptions.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_subscription_events_id'),
                    'subscription_events', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_events_subscription_id'),
                    'subscription_events', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_events_subscription_id'),
                  table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_id'),
                  table_name='subscription_events')
    op.drop_table('subscription_events')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_original_transaction_id'),
                  table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
