"""add created_by to error_reports

Revision ID: 9bff3ccb268c
Revises: a17d316260c4
Create Date: 2025-11-07 21:06:57.682868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bff3ccb268c'
down_revision: Union[str, None] = 'a17d316260c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error_reports', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'error_reports', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'error_reports', type_='foreignkey')
    op.drop_column('error_reports', 'created_by')
    # ### end Alembic commands ###
