"""add_partner_category_and_link_to_partners

Revision ID: c8d945fee32d
Revises: 53607864588d
Create Date: 2026-02-14 19:38:01.794327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d945fee32d'
down_revision: Union[str, None] = '53607864588d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_categories_id'), 'partner_categories', ['id'], unique=False)
    op.create_index(op.f('ix_partner_categories_name'), 'partner_categories', ['name'], unique=True)
    op.add_column('partners', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'partners', 'partner_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partners', type_='foreignkey')
    op.drop_column('partners', 'category_id')
    op.drop_index(op.f('ix_partner_categories_name'), table_name='partner_categories')
    op.drop_index(op.f('ix_partner_categories_id'), table_name='partner_categories')
    op.drop_table('partner_categories')
    # ### end Alembic commands ###
