"""Add unique constraints on product ean and brand name

Revision ID: ce21aae61203
Revises: 549797de1686
Create Date: 2025-07-03 21:24:57.845830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce21aae61203'
down_revision: Union[str, None] = '549797de1686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_index(op.f('ix_products_ean'), 'products', ['ean'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_ean'), table_name='products')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    # ### end Alembic commands ###
