"""Remove table_args from cosmetics 

Revision ID: d73e0c2d0933
Revises: 7055d8019d66
Create Date: 2025-07-18 15:22:35.461377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd73e0c2d0933'
down_revision: Union[str, None] = '7055d8019d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cosmetics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cosmetics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cosmetics', 'is_vegan',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cosmetics', 'is_cruelty_free',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cosmetics', 'is_cruelty_free',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cosmetics', 'is_vegan',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cosmetics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cosmetics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
