"""add_last_modified_by_to_products

Revision ID: db1c492c81be
Revises: 3413005589e3
Create Date: 2025-12-29 20:26:36.627600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1c492c81be'
down_revision: Union[str, None] = '3413005589e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('last_modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['last_modified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'last_modified_by')
    # ### end Alembic commands ###
