"""Product found report

Revision ID: e41d759f95f7
Revises: cefe9cfc10ae
Create Date: 2026-04-12 12:15:52.129020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41d759f95f7'
down_revision: Union[str, None] = 'cefe9cfc10ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_found_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_found_reports_created_at'), 'product_found_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_found_reports_ean'), 'product_found_reports', ['ean'], unique=False)
    op.create_index(op.f('ix_product_found_reports_id'), 'product_found_reports', ['id'], unique=False)
    op.create_index(op.f('ix_product_found_reports_shop_id'), 'product_found_reports', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_found_reports_shop_id'), table_name='product_found_reports')
    op.drop_index(op.f('ix_product_found_reports_id'), table_name='product_found_reports')
    op.drop_index(op.f('ix_product_found_reports_ean'), table_name='product_found_reports')
    op.drop_index(op.f('ix_product_found_reports_created_at'), table_name='product_found_reports')
    op.drop_table('product_found_reports')
    # ### end Alembic commands ###
