"""Add Additive table

Revision ID: eab9d5824d95
Revises: 0bc3352d9ae1
Create Date: 2026-01-17 20:34:11.768859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab9d5824d95'
down_revision: Union[str, None] = '0bc3352d9ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additives',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('e_number', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('status', sa.Enum('VEGAN', 'NON_VEGAN',
                                                'MAYBE_VEGAN', name='additivestatus'), nullable=True),
                    sa.Column('source', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_additives_e_number'),
                    'additives', ['e_number'], unique=True)
    op.create_index(op.f('ix_additives_id'), 'additives', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_additives_id'), table_name='additives')
    op.drop_index(op.f('ix_additives_e_number'), table_name='additives')
    op.drop_table('additives')
    # ### end Alembic commands ###
